# Generated by Django 6.0 on 2025-12-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GeneralSettings",
            new_name="GeneralSetting",
        ),
    ]
