# Generated by Django 6.0 on 2026-01-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_experiancesetting_generalsetting_imagesetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiancesetting',
            name='company_name',
            field=models.CharField(default='', max_length=255, verbose_name='Company Name'),
        ),
    ]
