# Generated by Django 6.0 on 2026-01-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_generalsettings_generalsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('file', models.FileField(blank=True, default='', max_length=255, upload_to='images/', verbose_name='File')),
            ],
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'verbose_name': 'General Setting', 'verbose_name_plural': 'General Settings'},
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created_at'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='parameters',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated_at'),
        ),
    ]
