# Generated by Django 6.0 on 2026-01-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_experiancesetting_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesetting',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
