# Generated by Django 6.0 on 2026-01-01 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_imagesetting_options_imagesetting_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('persentage', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Persentage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
