# Generated by Django 6.0 on 2026-01-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_imagesetting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
