# Generated by Django 6.0 on 2026-01-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_generalsetting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='parameters',
            field=models.TextField(blank=True, default='', verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
    ]
