# Generated by Django 6.0 on 2026-01-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_skillsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillsetting',
            options={'ordering': ['order'], 'verbose_name': 'Image Setting', 'verbose_name_plural': 'Image Settings'},
        ),
    ]
