# Generated by Django 6.0 on 2026-01-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_generalsetting_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('scholl_name', models.CharField(default='', max_length=255, verbose_name='Company Name')),
                ('major', models.CharField(blank=True, default='', max_length=255, verbose_name='Job Title')),
                ('department', models.CharField(blank=True, default='', max_length=255, verbose_name='Location')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Education Setting',
                'verbose_name_plural': 'Education Settings',
                'ordering': ['-start_date'],
            },
        ),
    ]
