# Generated by Django 6.0 on 2026-01-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_educationsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('link', models.URLField(default='', max_length=255, verbose_name='Link')),
                ('icon', models.CharField(default='', max_length=255, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social Setting',
                'verbose_name_plural': 'Social Settings',
                'ordering': ['-order'],
            },
        ),
        migrations.AlterField(
            model_name='educationsetting',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='educationsetting',
            name='major',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='major'),
        ),
        migrations.AlterField(
            model_name='educationsetting',
            name='scholl_name',
            field=models.CharField(default='', max_length=255, verbose_name='scholl name'),
        ),
    ]
