# Generated by Django 6.0 on 2026-01-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_socialsetting_alter_educationsetting_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.FileField(blank=True, default='', max_length=255, upload_to='image/', verbose_name='File'),
        ),
    ]
