# Generated by Django 6.0 on 2026-01-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='Email')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='Subject')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('-created_at',),
            },
        ),
    ]
